### ISSUE TITLE
Remove id property from persona

### ISSUE THREAD

**Issue by JeremyCroff** [intuit/saloon#19]
We can assign a unique ID on the fly just like the path property.
thoughts

**Comment by jwils0n** [comment]
Do we even need an `id`? It made sense back when `parentData` had the entire seeded persona instead of just the parent resources, but not so much anymore.

My one thought is, what if `OutputStore.get` returned a class that helped in retrieving values instead of just the seeded persona? That way, you could do something like `output.get('taxReturnId')` instead of having to do `output.user[0].firm[0].client[1].taxReturn[3]`.

**Comment by JeremyCroff** [comment]
Agreed 👍
